site_name: Optimism Java
site_url: https://optimism-java.github.io

# Repository
repo_url: https://github.com/optimism-java
repo_name: OP-Java


# Configuration
theme:
  name: material
  logo: assets/images/image.png
  palette:
    primary: red
  features:
    - announce.dismiss
    - content.code.copy
    - navigation.indexes
    - navigation.tabs
  icon:
    repo: fontawesome/brands/github

# Extensions
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

# Page tree
nav:
  - Home: index.md
  - Hildr:
    - hildr_repo/index.md
    - Run a Hildr node:
      - Use the jar: hildr_repo/use_jar.md
      - Use docker: hildr_repo/use_docker.md
  - Op-Besu:
    - op_besu_repo/index.md
    - Run a Op-Besu node:
      - Use the packaged bianries: op_besu_repo/use_binaries.md
      - Use Docker: op_besu_repo/use_docker.md