---
name: Check for lint/build errors

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code Base, Spelling
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Lint
        uses: Consensys/docs-gha/lint@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linkCheck:
    name: Link Checking
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file-extensions: [".md", ".mdx"]
    steps:
      - uses: actions/checkout@v4
      - name: LinkCheck
        uses: Consensys/docs-gha/linkcheck@main
        with:
          FILE_EXTENSION: '${{ matrix.file-extensions }}'
          CONFIG_FILE: 'mlc_config.json'
