---
name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Build
        uses: Consensys/docs-gha/release@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
